// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package bootstrap

import (
	"github.com/flutterffi/pfGoPlus/internal/app"
	"github.com/flutterffi/pfGoPlus/internal/config"
)

// Injectors from wire.go:

func InitializeHTTPApp() (*app.HTTPApp, error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, err
	}
	logger, err := NewLogger(configConfig)
	if err != nil {
		return nil, err
	}
	db, err := NewReadyDatabase(configConfig, logger)
	if err != nil {
		return nil, err
	}
	provider, err := NewTelemetry(configConfig, logger)
	if err != nil {
		return nil, err
	}
	service := NewAuthService(configConfig)
	handler := NewAuthHandler(service)
	repository := NewTodoRepository(db)
	todoService := NewTodoService(repository)
	todoBackend, err := NewTodoBackend(configConfig, logger, todoService)
	if err != nil {
		return nil, err
	}
	api := NewTodoAPI(todoBackend)
	todoHandler := NewTodoHandler(api, service)
	edge := NewBFF(configConfig, handler, todoHandler, provider)
	engine := NewHTTPRouter(logger, provider, edge)
	httpHandler := NewHTTPHandler(engine)
	v := NewHTTPAppCleanups(todoBackend)
	httpApp := app.NewHTTPApp(configConfig, logger, db, provider, httpHandler, v...)
	return httpApp, nil
}

func InitializeGRPCApp() (*app.GRPCApp, error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, err
	}
	logger, err := NewLogger(configConfig)
	if err != nil {
		return nil, err
	}
	db, err := NewReadyDatabase(configConfig, logger)
	if err != nil {
		return nil, err
	}
	provider, err := NewTelemetry(configConfig, logger)
	if err != nil {
		return nil, err
	}
	repository := NewTodoRepository(db)
	service := NewTodoService(repository)
	todoServiceServer := NewTodoGRPCService(service)
	server := NewGRPCServer(logger, provider, todoServiceServer)
	grpcApp := app.NewGRPCApp(configConfig, logger, db, provider, server)
	return grpcApp, nil
}
